version: "3"
services:
  bpm:
    build: 
      context: ./sim-dev-bpm
      args: 
        - SRC_GIT_REPO=http://docker:docker12345@192.168.21.46/ancine/sin-bpm.git
        - SRC_GIT_BRANCH=feature/back-Atualiza-dependencias-para-eap6.4.16-bpms6.4.4
    image: ancine/sim-dev-bpm:latest
    ports:
      - "8001:8001"
      - "8080:8080"
      - "9990:9990"
    volumes:
      - ./src:/opt/jboss/src
      - ./data:/opt/jboss/data
      - ./logs:/opt/jboss/eap/standalone/log
      - ~/.m2:/opt/jboss/.m2